# Generated by Django 5.0.6 on 2026-08-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('plant', models.CharField(choices=[('HRS', 'HRS - Silvassa'), ('RTP_ACHHAD', 'RTP - Achhad'), ('RTP_VAPI', 'RTP - Vapi')], max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('import_validity_end', models.DateField(blank=True, null=True)),
                ('export_obligation_end', models.DateField(blank=True, null=True)),
                ('extension_1_end', models.DateField(blank=True, null=True)),
                ('extension_2_end', models.DateField(blank=True, null=True)),
                ('auto_extension_end', models.DateField(blank=True, null=True)),
                ('eodc_status', models.CharField(choices=[('open', 'Open'), ('closed', 'EODC Closed')], default='open', max_length=20)),
                ('total_authorised_cif_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('letter_drive_file_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('action', models.CharField(max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'HRS - Silvassa'), ('RTP_ACHHAD', 'RTP - Achhad'), ('RTP_VAPI', 'RTP - Vapi')], max_length=20)),
                ('doc_type', models.CharField(choices=[('domestic', 'Domestic'), ('import', 'Import')], max_length=20)),
                ('po_number_hint', models.CharField(blank=True, max_length=50)),
                ('drive_folder_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('batched', 'Batched'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('batch_request_file_id', models.CharField(blank=True, max_length=100)),
                ('batch_result_file_id', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=10)),
                ('material_description', models.CharField(max_length=500)),
                ('sion_norm', models.CharField(blank=True, max_length=50)),
                ('authorised_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('consumed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='LicensePOUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_description', models.CharField(blank=True, max_length=500)),
                ('qty_used', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('value_used', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='POFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_text', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('extraction', 'Extraction'), ('po_vs_mir', 'PO vs MIR'), ('mir_vs_stock', 'MIR vs Stock'), ('manual_correction', 'Manual Correction')], default='extraction', max_length=30)),
                ('submitted_by_email', models.EmailField(blank=True, max_length=254)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('hsn', models.CharField(blank=True, max_length=20)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('plant', models.CharField(choices=[('HRS', 'HRS - Silvassa'), ('RTP_ACHHAD', 'RTP - Achhad'), ('RTP_VAPI', 'RTP - Vapi')], max_length=20)),
                ('doc_type', models.CharField(choices=[('domestic', 'Domestic'), ('import', 'Import')], max_length=20)),
                ('drive_folder_id', models.CharField(blank=True, max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('vendor_gstin', models.CharField(blank=True, max_length=20)),
                ('ship_to', models.TextField(blank=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('tax_type', models.CharField(blank=True, max_length=20)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total_incl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('incoterms', models.CharField(blank=True, max_length=50)),
                ('delivery_mode', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('material_inwarded', 'Material Inwarded'), ('received_in_inventory', 'Received in Inventory')], default='ordered', max_length=30)),
                ('extraction_confidence', models.CharField(choices=[('high', 'High'), ('low', 'Low')], default='high', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'HRS - Silvassa'), ('RTP_ACHHAD', 'RTP - Achhad'), ('RTP_VAPI', 'RTP - Vapi')], max_length=20)),
                ('material_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('snapshot_date', models.DateField()),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('plants', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='extractionqueue',
            constraint=models.UniqueConstraint(fields=('drive_folder_id',), name='uniq_extraction_queue_folder'),
        ),
        migrations.AddField(
            model_name='licenseitem',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.advancelicense'),
        ),
        migrations.AddField(
            model_name='licensepousage',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_usages', to='core.advancelicense'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['plant', 'doc_type'], name='core_purcha_plant_483abf_idx'),
        ),
        migrations.AddField(
            model_name='poitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder'),
        ),
        migrations.AddField(
            model_name='poflag',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.purchaseorder'),
        ),
        migrations.AddField(
            model_name='licensepousage',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_usages', to='core.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['plant', 'snapshot_date'], name='core_stocks_plant_7b9e95_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocksnapshot',
            constraint=models.UniqueConstraint(fields=('plant', 'material_code', 'snapshot_date'), name='uniq_stock_snapshot'),
        ),
    ]
