# Generated by Django 5.0.6 on 2026-08-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'HRS - Silvassa'), ('RTP_ACHHAD', 'RTP - Achhad'), ('RTP_VAPI', 'RTP - Vapi')], max_length=20, unique=True)),
                ('mir_row_count', models.IntegerField(default=0)),
                ('stock_row_count', models.IntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
