# Generated by Django 5.0.6 on 2026-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plantfilestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poitem',
            name='hsn',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='incoterms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
