# Generated by Django 5.0.6 on 2026-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_poitem_hsn_alter_poitem_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseitem',
            name='material_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='licensepousage',
            name='material_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poflag',
            name='flag_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poitem',
            name='description',
            field=models.TextField(),
        ),
    ]
