# Generated by Django 5.0.6 on 2026-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_licenseitem_material_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
