# Generated by Django 5.1.15 on 2026-09-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rtpachhadpolineitem_rtpachhadmirentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtpachhadmirentry',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
