# Generated by Django 5.2.17 on 2026-09-03 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ptuser_otpcode_trusteddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=32)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pt_audit_log',
                'ordering': ['-timestamp'],
                'managed': True,
                'indexes': [models.Index(fields=['actor_id', 'timestamp'], name='pt_audit_lo_actor_i_df6fc5_idx')],
            },
        ),
    ]
