# Generated by Django 5.2.17 on 2026-09-04 07:21

from django.db import migrations, models


def _dedupe_otp_codes(apps, schema_editor):
    """Keep only the most recently created OTPCode row per email.

    A prior race in generate_otp() (delete-then-create, not atomic) could
    leave two rows for the same email if two OTP requests overlapped -
    exactly the scenario the new unique constraint on `email` (below)
    prevents going forward. Clear out any such leftovers first so the
    AlterField doesn't fail against a production DB that already has them.
    """
    OTPCode = apps.get_model('core', 'OTPCode')
    seen_emails = set()
    for row in OTPCode.objects.order_by('email', '-created_at'):
        if row.email in seen_emails:
            row.delete()
        else:
            seen_emails.add(row.email)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ptauditlog'),
    ]

    operations = [
        migrations.RunPython(_dedupe_otp_codes, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='otpcode',
            name='pt_otp_code_email_1f32e0_idx',
        ),
        migrations.RemoveField(
            model_name='otpcode',
            name='used',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
