# Generated by Django 5.2.17 on 2026-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_otpcode_pt_otp_code_email_1f32e0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsmirentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text="False once a sync no longer sees this source_row_ref in the sheet (row deleted, or the file shrank). Rows are identified by sheet row NUMBER, which shifts if a row is inserted/deleted above it - deactivating instead of deleting on disappearance avoids destroying PO<->MIR match history (CASCADE) for a row that a shift merely renumbered, while still excluding stale rows from matching. See sync_mir.py's module docstring."),
        ),
        migrations.AddField(
            model_name='hrsstocklot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="False once a sync no longer sees this source_row_ref in the sheet (lot sold out/removed, or a row shift). Deactivating instead of deleting preserves this lot's HRSStockSnapshot history (CASCADE) and excludes it from matching - see HRSMIREntry.is_active's help_text for the full row-shift reasoning."),
        ),
        migrations.AddField(
            model_name='rtpachhadmirentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text="See HRSMIREntry.is_active's help_text - same row-shift/CASCADE reasoning, Achhad's copy."),
        ),
        migrations.AddField(
            model_name='rtpachhadstocklot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="See HRSStockLot.is_active's help_text - same row-shift/CASCADE reasoning, Achhad's copy."),
        ),
        migrations.AddField(
            model_name='rtpvapimirentry',
            name='is_active',
            field=models.BooleanField(default=True, help_text="See HRSMIREntry.is_active's help_text - same row-shift/CASCADE reasoning, Vapi's copy."),
        ),
        migrations.AddField(
            model_name='rtpvapistocklot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="See HRSStockLot.is_active's help_text - same row-shift/CASCADE reasoning, Vapi's copy."),
        ),
    ]
