# Generated by Django 5.2.17 on 2026-09-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_import_purchase_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptuser',
            name='plants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='DomesticPOCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad')], max_length=20)),
                ('po_number', models.CharField(max_length=100)),
                ('item_id', models.CharField(blank=True, help_text='Blank for a PO-level field correction; set for a line-item field correction.', max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('corrected_by_email', models.CharField(blank=True, max_length=255)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domestic_po_corrections', to='core.ptuser')),
            ],
            options={
                'ordering': ['-corrected_at'],
                'indexes': [models.Index(fields=['plant', 'po_number'], name='core_domest_plant_71ca32_idx')],
            },
        ),
    ]
