# Generated by Django 5.2.17 on 2026-09-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_domestic_po_correction_ptuser_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser'),
        ),
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='dismissed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser'),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='dismissed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rtpachhadmirstockmatch',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadmirstockmatch',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser'),
        ),
        migrations.AddField(
            model_name='rtpachhadmirstockmatch',
            name='dismissed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser'),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='dismissed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser'),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='dismissed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser'),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='dismissed_reason',
            field=models.TextField(blank=True),
        ),
    ]
