# Generated by Django 5.2.17 on 2026-09-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hrsmirstockmatch_dismissed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSImportPOMirMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('po_number', 'PO number match (exact)'), ('weighted', 'Vendor-gated weighted match')], max_length=20)),
                ('match_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('qty_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('value_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('dismissed_by_override', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('mir_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_po_matches', to='core.hrsmirentry')),
                ('po_line_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mir_match', to='core.hrsimportpolineitem')),
            ],
        ),
        migrations.CreateModel(
            name='RTPAchhadImportPOMirMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('po_number', 'PO number match (exact)'), ('weighted', 'Vendor-gated weighted match')], max_length=20)),
                ('match_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('qty_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('value_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('dismissed_by_override', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('mir_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_po_matches', to='core.rtpachhadmirentry')),
                ('po_line_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mir_match', to='core.rtpachhadimportpolineitem')),
            ],
        ),
        migrations.CreateModel(
            name='RTPVapiImportPOMirMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('po_number', 'PO number match (exact)'), ('weighted', 'Vendor-gated weighted match')], max_length=20)),
                ('match_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('qty_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('value_diff_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('dismissed_by_override', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('mir_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_po_matches', to='core.rtpvapimirentry')),
                ('po_line_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mir_match', to='core.rtpvapiimportpolineitem')),
            ],
        ),
    ]
