# Generated by Django 5.2.17 on 2026-09-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hrsimportpomirmatch_rtpachhadimportpomirmatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad')], max_length=20)),
                ('lot_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('corrected_by_email', models.CharField(blank=True, max_length=255)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_corrections', to='core.ptuser')),
            ],
            options={
                'ordering': ['-corrected_at'],
                'indexes': [models.Index(fields=['plant', 'lot_id'], name='core_materi_plant_ed3231_idx')],
            },
        ),
    ]
