# Generated by Django 5.2.17 on 2026-09-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_materialcorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad')], max_length=20)),
                ('po_number', models.CharField(max_length=100)),
                ('flag_key', models.CharField(max_length=150)),
                ('dismissed', models.BooleanField(default=True)),
                ('dismissed_by_email', models.CharField(blank=True, max_length=255)),
                ('dismissed_reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_dismissals', to='core.ptuser')),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'po_number'], name='core_flagdi_plant_57ef8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'po_number', 'flag_key'), name='uniq_flag_dismissal')],
            },
        ),
    ]
