# Generated by Django 5.2.17 on 2026-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_hash_trusted_device_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('device_revoked', 'Trusted device revoked')], db_index=True, max_length=32),
        ),
    ]
