# Generated by Django 5.2.17 on 2026-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_ptauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='source',
            field=models.CharField(choices=[('po_csv', 'Purchase Order master CSV'), ('mir', 'MIR (Material Inward Register)'), ('stock', 'Raw Material Stock'), ('import_po_csv', 'Import Purchase Order master CSV'), ('match', 'PO<->MIR<->Stock matching')], max_length=20),
        ),
    ]
