# Generated by Django 5.2.17 on 2026-09-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_syncrun_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticpocorrection',
            name='reason',
            field=models.TextField(blank=True, default='', help_text="See ImportPOCorrection.reason's help_text - same field, same purpose."),
        ),
        migrations.AddField(
            model_name='importpocorrection',
            name='reason',
            field=models.TextField(blank=True, default='', help_text="Why the requester believes the old value was wrong / what they verified the new value against - optional, entered in the 'Submit a Correction' panel on the Flags & Corrections tab."),
        ),
        migrations.AddField(
            model_name='materialcorrection',
            name='reason',
            field=models.TextField(blank=True, default='', help_text="See ImportPOCorrection.reason's help_text - same field, same purpose."),
        ),
    ]
