# Generated by Django 5.2.17 on 2026-09-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_domesticpocorrection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Mirrors the token's own exp claim - lets a future cleanup command purge rows whose token would have expired naturally anyway. Not purged automatically yet.")),
            ],
            options={
                'db_table': 'pt_revoked_refresh_tokens',
                'indexes': [models.Index(fields=['jti'], name='pt_revoked__jti_6d4a2c_idx')],
            },
        ),
    ]
