# Generated by Django 5.2.17 on 2026-09-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_revokedrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptuser',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ptuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
