# Generated by Django 5.2.17 on 2026-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ptuser_failed_login_attempts_ptuser_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptuser',
            name='token_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ptauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('device_revoked', 'Trusted device revoked'), ('sessions_revoked', 'All sessions revoked (log out everywhere)')], db_index=True, max_length=32),
        ),
    ]
