# Generated by Django 5.2.17 on 2026-09-05 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_stock_snapshot_date_lot_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad')], max_length=20)),
                ('match_type', models.CharField(choices=[('po_mir', 'PO <-> MIR'), ('import_po_mir', 'Import PO <-> MIR'), ('mir_stock', 'MIR <-> Stock')], max_length=20)),
                ('match_id', models.PositiveIntegerField()),
                ('verdict', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('unsure', 'Unsure')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reviews', to='core.ptuser')),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'match_type', 'match_id'], name='core_matchr_plant_308b04_idx')],
            },
        ),
    ]
