# Generated by Django 5.2.17 on 2026-09-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_matchreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='field_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='field_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='field_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='field_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='field_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='field_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
