# Generated by Django 5.2.17 on 2026-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_uom_mismatch_field_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='severity',
            field=models.CharField(blank=True, choices=[('rounding', 'Rounding'), ('minor', 'Minor'), ('material', 'Material')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='severity',
            field=models.CharField(blank=True, choices=[('rounding', 'Rounding'), ('minor', 'Minor'), ('material', 'Material')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='severity',
            field=models.CharField(blank=True, choices=[('rounding', 'Rounding'), ('minor', 'Minor'), ('material', 'Material')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='severity',
            field=models.CharField(blank=True, choices=[('rounding', 'Rounding'), ('minor', 'Minor'), ('material', 'Material')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='severity',
            field=models.CharField(blank=True, choices=[('rounding', 'Rounding'), ('minor', 'Minor'), ('material', 'Material')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='severity',
            field=models.CharField(blank=True, choices=[('rounding', 'Rounding'), ('minor', 'Minor'), ('material', 'Material')], max_length=10, null=True),
        ),
    ]
