# Generated by Django 5.2.17 on 2026-09-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_match_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad')], max_length=20)),
                ('source_type', models.CharField(choices=[('po_line_item', 'PO line item'), ('mir_entry', 'MIR entry'), ('stock_lot', 'Stock lot')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('check_name', models.CharField(max_length=50)),
                ('expected', models.DecimalField(decimal_places=4, max_digits=16)),
                ('actual', models.DecimalField(decimal_places=4, max_digits=16)),
                ('detected_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'source_type'], name='core_dataqu_plant_f8f844_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'source_type', 'source_id', 'check_name'), name='uniq_data_quality_flag')],
            },
        ),
    ]
