# Generated by Django 5.2.17 on 2026-09-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_data_quality_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrspomirmatch',
            name='data_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='final_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="PO's Total Inclusive Value vs MIR's Final/Invoice Value - same single-line-item caveat as taxable_value_diff_pct.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='material_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='po_number_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='qty_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='tax_type_mismatch',
            field=models.BooleanField(default=False, help_text="True when the PO's declared Tax Type (IGST vs CGST+SGST) is structurally inconsistent with which GST columns MIR actually populated."),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='taxable_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="PO's Total Value vs MIR's Taxable Value - only computed for a single-line-item PO, see matching_core.py's _po_matchable() docstring for why.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='data_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='final_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='material_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='po_number_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='qty_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='tax_type_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='taxable_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='data_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='final_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='material_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='po_number_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='qty_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='tax_type_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='taxable_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hrspomirmatch',
            name='tier',
            field=models.CharField(choices=[('po_number', 'PO number match (exact)'), ('material', 'Material description match'), ('weighted', 'Vendor-gated weighted match (legacy, pre-2026-09-07)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rtpachhadpomirmatch',
            name='tier',
            field=models.CharField(choices=[('po_number', 'PO number match (exact)'), ('material', 'Material description match'), ('weighted', 'Vendor-gated weighted match (legacy, pre-2026-09-07)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rtpvapipomirmatch',
            name='tier',
            field=models.CharField(choices=[('po_number', 'PO number match (exact)'), ('material', 'Material description match'), ('weighted', 'Vendor-gated weighted match (legacy, pre-2026-09-07)')], max_length=20),
        ),
    ]
