# Generated by Django 5.2.17 on 2026-09-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_imports_data_mismatch_hrs_achhad'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='data_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='date_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='material_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='qty_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="MIR's net/taxable value (config.mir_value) vs Stock's own Value column.", max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hrsmirstockmatch',
            name='qty_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Stock's REC vs MIR's Qty - only ever populated when REC is nonzero AND this candidate matched via date_matched (see match_mir_entry_stock()'s docstring).", max_digits=6, null=True),
        ),
    ]
