# Generated by Django 5.2.17 on 2026-09-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rtpachhadmirstockmatch_data_mismatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='data_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='date_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='material_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='qty_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="MIR's net/taxable value (config.mir_value) vs the derived REC x Basic Rate for this lot.", max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rtpvapimirstockmatch',
            name='qty_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Stock's REC vs MIR's Qty - only ever populated when REC is nonzero AND this candidate matched via date_matched (see match_mir_entry_stock()'s docstring).", max_digits=6, null=True),
        ),
    ]
