# Generated by Django 5.2.17 on 2026-09-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rtpvapimirstockmatch_data_mismatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='data_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='final_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='material_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='po_number_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='qty_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='tax_type_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='taxable_value_diff_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rtpvapiimportpomirmatch',
            name='tier',
            field=models.CharField(choices=[('po_number', 'PO number match (exact)'), ('material', 'Material description match'), ('weighted', 'Vendor-gated weighted match (legacy, pre-2026-09 imports redesign)')], max_length=20),
        ),
    ]
