# Generated by Django 5.2.17 on 2026-09-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_domestic_purchase_and_rm_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hrsdomesticpolineitem',
            new_name='core_hrsdom_item_id_e406bd_idx',
            old_name='core_hrspol_item_id_96da82_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsdomesticpolineitem',
            new_name='core_hrsdom_descrip_4ecefd_idx',
            old_name='core_hrspol_descrip_778cac_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsdomesticpurchaseorder',
            new_name='core_hrsdom_vendor__cc9d65_idx',
            old_name='core_hrspur_vendor__cfba0b_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsdomesticpurchaseorder',
            new_name='core_hrsdom_po_driv_b22bd0_idx',
            old_name='core_hrspur_po_driv_1a8afb_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsrmlot',
            new_name='core_hrsrml_descrip_cfda8c_idx',
            old_name='core_hrssto_descrip_058486_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsrmlot',
            new_name='core_hrsrml_party_n_9d44d9_idx',
            old_name='core_hrssto_party_n_bf29ca_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsrmlot',
            new_name='core_hrsrml_sap_ite_fcc6d1_idx',
            old_name='core_hrssto_sap_ite_e13605_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsrmsnapshot',
            new_name='core_hrsrms_snapsho_ef171e_idx',
            old_name='core_hrssto_snapsho_f1f245_idx',
        ),
        migrations.RenameIndex(
            model_name='hrsrmsnapshot',
            new_name='core_hrsrms_snapsho_f2432e_idx',
            old_name='core_hrssto_snapsho_24d802_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhaddomesticpolineitem',
            new_name='core_rtpach_item_id_faa1d3_idx',
            old_name='core_rtpach_item_id_ebb83b_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhaddomesticpolineitem',
            new_name='core_rtpach_descrip_921c40_idx',
            old_name='core_rtpach_descrip_c12e13_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhaddomesticpurchaseorder',
            new_name='core_rtpach_vendor__f7ab7b_idx',
            old_name='core_rtpach_vendor__e09781_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhaddomesticpurchaseorder',
            new_name='core_rtpach_po_driv_f97407_idx',
            old_name='core_rtpach_po_driv_a27714_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhadrmlot',
            new_name='core_rtpach_descrip_531fee_idx',
            old_name='core_rtpach_descrip_19c68f_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhadrmlot',
            new_name='core_rtpach_sap_cod_f105e6_idx',
            old_name='core_rtpach_sap_cod_65207d_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhadrmsnapshot',
            new_name='core_rtpach_snapsho_4bfc56_idx',
            old_name='core_rtpach_snapsho_a5a481_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpachhadrmsnapshot',
            new_name='core_rtpach_snapsho_639712_idx',
            old_name='core_rtpach_snapsho_3824c9_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapidomesticpolineitem',
            new_name='core_rtpvap_item_id_741904_idx',
            old_name='core_rtpvap_item_id_4254fb_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapidomesticpolineitem',
            new_name='core_rtpvap_descrip_5f535d_idx',
            old_name='core_rtpvap_descrip_937e35_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapidomesticpurchaseorder',
            new_name='core_rtpvap_vendor__861e22_idx',
            old_name='core_rtpvap_vendor__1a6da8_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapidomesticpurchaseorder',
            new_name='core_rtpvap_po_driv_3a3371_idx',
            old_name='core_rtpvap_po_driv_74a774_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapirmlot',
            new_name='core_rtpvap_descrip_9a7f82_idx',
            old_name='core_rtpvap_descrip_0fc7d9_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapirmlot',
            new_name='core_rtpvap_supplie_893b72_idx',
            old_name='core_rtpvap_supplie_ede921_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapirmlot',
            new_name='core_rtpvap_hsn_cod_c39eeb_idx',
            old_name='core_rtpvap_hsn_cod_639cbb_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapirmsnapshot',
            new_name='core_rtpvap_snapsho_b772f0_idx',
            old_name='core_rtpvap_snapsho_01e5bb_idx',
        ),
        migrations.RenameIndex(
            model_name='rtpvapirmsnapshot',
            new_name='core_rtpvap_snapsho_1b7daa_idx',
            old_name='core_rtpvap_snapsho_fb5b73_idx',
        ),
        migrations.AlterField(
            model_name='hrsrmlot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="False once a sync no longer sees this natural_key in the sheet (lot sold out/removed). Deactivating instead of deleting preserves this lot's HRSRMSnapshot history (CASCADE) and excludes it from matching - see HRSMIREntry.is_active's help_text for the same is_active/CASCADE reasoning (that model still keys on source_row_ref; this one no longer does)."),
        ),
        migrations.AlterField(
            model_name='rtpachhadrmlot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="See HRSRMLot.is_active's help_text - same row-shift/CASCADE reasoning, Achhad's copy."),
        ),
        migrations.AlterField(
            model_name='rtpachhadrmlot',
            name='natural_key',
            field=models.CharField(blank=True, db_index=True, help_text="See HRSRMLot.natural_key's help_text. Achhad's key is weaker by necessity - no vendor column, so two lots of the same material are separated only by the occurrence counter (apps/services/stock_identity.py) - the same weaker-gate precedent matching_achhad.py already sets, still strictly better than a row number.", max_length=200),
        ),
        migrations.AlterField(
            model_name='rtpachhadrmlot',
            name='source_row_ref',
            field=models.CharField(blank=True, help_text="See HRSRMLot.source_row_ref's help_text - diagnostic only, Achhad's copy.", max_length=20),
        ),
        migrations.AlterField(
            model_name='rtpachhadrmlot',
            name='todays_stock',
            field=models.DecimalField(decimal_places=3, default=0, help_text="Sheet's own 'Closing' column - named todays_stock to match HRSRMLot's field name, since it plays the same role for matching/display.", max_digits=14),
        ),
        migrations.AlterField(
            model_name='rtpvapirmlot',
            name='is_active',
            field=models.BooleanField(default=True, help_text="See HRSRMLot.is_active's help_text - same row-shift/CASCADE reasoning, Vapi's copy."),
        ),
        migrations.AlterField(
            model_name='rtpvapirmlot',
            name='natural_key',
            field=models.CharField(blank=True, db_index=True, help_text="See HRSRMLot.natural_key's help_text - Vapi's copy, keyed on hsn_code/supplier_name (apps/services/stock_identity.py).", max_length=200),
        ),
        migrations.AlterField(
            model_name='rtpvapirmlot',
            name='plant_tag',
            field=models.CharField(blank=True, help_text="Stock sheet's own 'PLANT' column (e.g. 'HRS', 'RTP-1', 'RTP-2') - this single sheet covers several sub-plants/warehouses at once, same idea as HRSRMLot's own location_tag field.", max_length=20),
        ),
        migrations.AlterField(
            model_name='rtpvapirmlot',
            name='source_row_ref',
            field=models.CharField(blank=True, help_text="See HRSRMLot.source_row_ref's help_text - diagnostic only, Vapi's copy.", max_length=20),
        ),
    ]
