# Generated by Django 5.2.17 on 2026-09-07 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_core_hrspol_item_id_96da82_idx_core_hrsdom_item_id_e406bd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTPAchhadRMDailyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField()),
                ('received', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('issued', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('source_row_ref', models.CharField(blank=True, help_text='Sheet row number this came from at last sync - diagnostic only, same convention as RTPAchhadRMLot.source_row_ref.', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_movements', to='core.rtpachhadrmlot')),
            ],
            options={
                'indexes': [models.Index(fields=['stock_lot', 'movement_date'], name='core_rtpach_stock_l_8df92c_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock_lot', 'movement_date'), name='uniq_achhad_daily_movement_per_lot_per_day')],
            },
        ),
    ]
