# Generated by Django 5.2.17 on 2026-09-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rtpachhadrmdailymovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategoryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='As given in the reference list, verbatim.', max_length=500)),
                ('normalized_description', models.CharField(help_text="normalize_material(description) with any trailing '(item code)' suffix stripped first - the actual join key against every plant's own RM Lot description.", max_length=500, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, help_text="The reference list's own 'Subcategory (SAP Product Group)' column, label portion only (e.g. 'CARBON BLACK' from 'CARBON BLACK (RM-CB001)') - see subcategory_code for the code.", max_length=200)),
                ('subcategory_code', models.CharField(blank=True, help_text="e.g. 'RM-CB001' - reference/audit only.", max_length=50)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('sap_item_code', models.CharField(blank=True, help_text='Stored for reference/audit only - NOT the match key (see class docstring for why).', max_length=50)),
                ('source_row_ref', models.CharField(blank=True, help_text='Row number in the source file at last load.', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='core_materi_categor_34e709_idx'), models.Index(fields=['normalized_description'], name='core_materi_normali_2d3ad1_idx')],
            },
        ),
    ]
