# Generated by Django 5.2.17 on 2026-09-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_materialcategoryreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='final_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='net_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='taxable_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='final_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='net_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='taxable_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='final_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='net_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='taxable_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='final_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='net_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='taxable_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='final_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='net_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='taxable_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='final_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='net_value_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='taxable_value_mismatched',
            field=models.BooleanField(default=False),
        ),
    ]
