# Generated by Django 5.2.17 on 2026-09-09 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_hrsimportpomirmatch_final_value_mismatched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataqualityflag',
            name='plant',
            field=models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='domesticpocorrection',
            name='plant',
            field=models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flagdismissal',
            name='plant',
            field=models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importpocorrection',
            name='plant',
            field=models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchreview',
            name='plant',
            field=models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='materialcorrection',
            name='plant',
            field=models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='plant',
            field=models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='source',
            field=models.CharField(choices=[('po_csv', 'Purchase Order master CSV'), ('mir', 'MIR (Material Inward Register)'), ('stock', 'Raw Material Stock'), ('import_po_csv', 'Import Purchase Order master CSV'), ('match', 'PO<->MIR<->Stock matching'), ('rodtep', 'RoDTEP scrip ledger')], max_length=20),
        ),
        migrations.CreateModel(
            name='RodtepScrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_no', models.CharField(max_length=50)),
                ('script_date', models.DateField(blank=True, null=True)),
                ('sb_number', models.CharField(max_length=50)),
                ('sb_date', models.DateField(blank=True, null=True)),
                ('scroll_number', models.CharField(blank=True, max_length=50)),
                ('scroll_date', models.DateField(blank=True, null=True)),
                ('scroll_type', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_file_name', models.CharField(blank=True, help_text="The 'RODTEP-JNPT-<N>.xlsx' file this row was parsed from - lets a reviewer trace a row back to its source file.", max_length=255)),
                ('source_row_ref', models.CharField(blank=True, max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rodtep_scroll_entry',
                'indexes': [models.Index(fields=['script_no'], name='rodtep_scro_script__b6cd15_idx')],
                'constraints': [models.UniqueConstraint(fields=('script_no', 'sb_number'), name='uniq_rodtep_script_sb')],
            },
        ),
        migrations.CreateModel(
            name='RodtepUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_no', models.CharField(db_index=True, max_length=50)),
                ('used_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('boe_number', models.CharField(blank=True, help_text='Primary join key against *ImportPOLineItem.boe_number.', max_length=50)),
                ('import_po_number', models.CharField(blank=True, max_length=50)),
                ('used_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rodtep_usage_entries', to='core.ptuser')),
            ],
            options={
                'db_table': 'rodtep_usage',
                'ordering': ['-used_date', '-created_at'],
            },
        ),
    ]
