# Generated by Django 5.2.17 on 2026-09-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_dataqualityflag_plant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('iec', models.CharField(blank=True, max_length=50)),
                ('cif_value_authorized', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fob_value_export_target', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('export_product_description', models.TextField(blank=True)),
                ('export_validity_date', models.DateField(blank=True, null=True)),
                ('import_validity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('synced_from_row_hash', models.CharField(blank=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'advance_license',
                'ordering': ['license_number'],
            },
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='source',
            field=models.CharField(choices=[('po_csv', 'Purchase Order master CSV'), ('mir', 'MIR (Material Inward Register)'), ('stock', 'Raw Material Stock'), ('import_po_csv', 'Import Purchase Order master CSV'), ('match', 'PO<->MIR<->Stock matching'), ('rodtep', 'RoDTEP scrip ledger'), ('advance_license', 'Advance License ledger')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdvanceLicenseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_description', models.CharField(blank=True, max_length=255)),
                ('itchs_code', models.CharField(blank=True, max_length=20)),
                ('qty_authorized', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('cif_value_authorized', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('duty_saved_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('boe_number', models.CharField(blank=True, max_length=50)),
                ('boe_date', models.DateField(blank=True, null=True)),
                ('import_po_number', models.CharField(blank=True, max_length=50)),
                ('qty_imported', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('value_imported', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.advancelicense')),
            ],
            options={
                'db_table': 'advance_license_material',
                'ordering': ['id'],
            },
        ),
    ]
