# Generated by Django 5.2.17 on 2026-09-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_advancelicense_alter_syncrun_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deleted', 'User deleted'), ('device_revoked', 'Trusted device revoked'), ('sessions_revoked', 'All sessions revoked (log out everywhere)')], db_index=True, max_length=32),
        ),
    ]
