# Generated by Django 5.2.17 on 2026-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_ptauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsmirstockmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadmirstockmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapimirstockmatch',
            name='uom_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
