# Generated by Django 5.2.17 on 2026-09-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_hrsmirstockmatch_uom_mismatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Consumption Report'), ('monthly', 'Monthly Consumption Report')], max_length=10)),
                ('plant', models.CharField(max_length=20)),
                ('period_key', models.CharField(help_text="Daily report: ISO date. Monthly report: 'YYYY-MM'.", max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pt_report_send_log',
                'constraints': [models.UniqueConstraint(fields=('report_type', 'plant', 'period_key'), name='uniq_report_send_per_period')],
            },
        ),
    ]
