# Generated by Django 5.2.17 on 2026-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_reportsendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpvapimirentry',
            name='sap_po_number',
            field=models.CharField(blank=True, help_text="MIR's own 'SAP P.O' field (column D) - empty on every row confirmed 2026-09-10, kept for forward compatibility. Not the same column as po_number_raw (which reads the newer, actually-populated 'PURCHASE ORDER' column added 2026-09-11) - don't conflate the two.", max_length=100),
        ),
        migrations.AlterField(
            model_name='rtpvapimirentry',
            name='po_number_raw',
            field=models.CharField(blank=True, help_text="Sourced from the MIR sheet's 'PURCHASE ORDER' column (added 2026-09-11 at the project owner's request specifically for better PO<->MIR matching - column K, inserted after 'STATE', shifting every later column right by one - see vapi_mir.py's module docstring). Before this the sheet had no populated PO-number column at all (the separate, still-present 'SAP P.O' field - see sap_po_number - was 100% blank on every row checked). Same reliability caveat as HRSMIREntry.po_number_raw: a tier-1 shortcut only, never a sole join key.", max_length=100),
        ),
    ]
