# Generated by Django 5.2.17 on 2026-09-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rtpvapimirentry_sap_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpvapirmlot',
            name='batch_no',
            field=models.CharField(blank=True, help_text="Stock sheet's 'Batch No.' column (E), which replaced 'Sub Category' in place on 2026-09-12 - same column position, new meaning. Real values are vendor/lot batch codes ('HRS-25', '230626GIFL2590') or a literal '-' placeholder; 166 of 168 live rows are populated. Vapi only - HRS's Stock sheet still has a genuine 'Sub Category' at E, and Achhad's sheet has neither column.", max_length=100),
        ),
        migrations.AlterField(
            model_name='rtpvapirmlot',
            name='sub_category',
            field=models.CharField(blank=True, help_text="No longer sourced from the Stock sheet. Column E held 'Sub Category' until 2026-09-12, when the Vapi plant renamed it to 'Batch No.' and repurposed its contents - see batch_no. Existing values are the last real sub-categories the sheet carried and are left in place (this field is audit/Edit-Everywhere only, never displayed - the materials API shows MaterialCategoryReference's canonical subcategory instead), but nothing writes to it now.", max_length=100),
        ),
    ]
