# Generated by Django 5.2.17 on 2026-09-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rtpvapirmlot_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='vendor_matched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='vendor_matched',
            field=models.BooleanField(default=True),
        ),
    ]
