# Generated by Django 5.2.17 on 2026-09-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rtpachhadimportpomirmatch_vendor_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='vendor_matched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='vendor_matched',
            field=models.BooleanField(default=True),
        ),
    ]
