# Generated by Django 5.2.17 on 2026-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_hrsimportpomirmatch_vendor_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='qty_over_delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='qty_over_delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='qty_over_delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='qty_over_delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='qty_over_delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='qty_over_delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
