# Generated by Django 5.2.17 on 2026-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_hrsimportpomirmatch_qty_over_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsdomesticpurchaseorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hrsimportpurchaseorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtpachhaddomesticpurchaseorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpurchaseorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtpvapidomesticpurchaseorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpurchaseorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
