# Generated by Django 5.2.17 on 2026-09-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_hrsdomesticpurchaseorder_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='vendor_matched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='vendor_matched',
            field=models.BooleanField(default=True),
        ),
    ]
