# Generated by Django 5.2.17 on 2026-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_rtpvapiimportpomirmatch_vendor_matched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='source',
            field=models.CharField(choices=[('po_csv', 'Purchase Order master CSV'), ('mir', 'MIR (Material Inward Register)'), ('stock', 'Raw Material Stock'), ('import_po_csv', 'Import Purchase Order master CSV'), ('match', 'PO<->MIR<->Stock matching'), ('rodtep', 'RoDTEP scrip ledger'), ('advance_license', 'Advance License ledger'), ('consumption', 'Raw material consumption ledger')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConsumptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20)),
                ('material_key', models.CharField(max_length=255)),
                ('material_description', models.CharField(blank=True, max_length=500)),
                ('lot_ref', models.CharField(blank=True, help_text="'<model name>#<pk>' of the *RMLot this interval belongs to - a plain string, not an FK, because this one table spans three per-plant lot models.", max_length=255)),
                ('kind', models.CharField(max_length=20)),
                ('interval_start', models.DateField()),
                ('interval_end', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, help_text="The event's real size as the issue book reports it - recorded at full size even when excluded, so 'what would this have added' is answerable.", max_digits=16)),
                ('balance_quantity', models.DecimalField(decimal_places=3, help_text='What the pre-2026-09-21 balance-drawdown method would have counted for this same interval. On a restatement the two differ enormously - that gap is the whole reason this column exists.', max_digits=16)),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-interval_end', 'material_key'],
                'indexes': [models.Index(fields=['plant', 'interval_end'], name='core_consum_plant_d7c40c_idx'), models.Index(fields=['plant', 'kind'], name='core_consum_plant_6a84b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'lot_ref', 'interval_start', 'interval_end', 'kind'), name='uniq_consumption_event_per_lot_interval')],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumptionDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20)),
                ('material_key', models.CharField(help_text="parsers.common.normalize_material(description) - see this model's docstring for why this is NOT *RMLot.natural_key and not a material code.", max_length=255)),
                ('consumption_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('quality', models.CharField(help_text="consumption_engine classification: 'counted' (observed on a single day) or 'spread' (one day's share of a multi-day interval, i.e. a snapshot gap).", max_length=20)),
                ('material_description', models.CharField(blank=True, max_length=500)),
                ('material_code', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('uom', models.CharField(blank=True, max_length=20)),
                ('lot_count', models.IntegerField(default=1, help_text="How many *RMLot rows contributed to this day's figure - 1 at Achhad/Vapi for almost everything, more at HRS where one material is split across vendor lots.")),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-consumption_date', 'material_key'],
                'indexes': [models.Index(fields=['plant', 'consumption_date'], name='core_materi_plant_d14b39_idx'), models.Index(fields=['plant', 'material_key', 'consumption_date'], name='core_materi_plant_6d5781_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'material_key', 'consumption_date'), name='uniq_consumption_per_material_per_day')],
            },
        ),
    ]
