# Generated by Django 5.2.17 on 2026-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_syncrun_source_consumptionevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20)),
                ('coverage_date', models.DateField()),
                ('observed', models.BooleanField(default=True, help_text="True when at least one lot had a single-day interval ending here (a directly observed day). False when every interval covering it spanned several days, so the day is only reachable by interpolation - see consumption_engine's `spread`.")),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-coverage_date'],
                'indexes': [models.Index(fields=['plant', 'coverage_date'], name='core_consum_plant_86bb62_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'coverage_date'), name='uniq_consumption_coverage_per_day')],
            },
        ),
    ]
