# Generated by Django 5.2.17 on 2026-09-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_consumptioncoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrspomirmatch',
            name='manually_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='manually_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='manually_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ManualMirMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20)),
                ('po_number', models.CharField(max_length=100)),
                ('item_ref', models.CharField(help_text='Zero-based position of the line item within its PO, as a string. See docstring.', max_length=50)),
                ('item_description', models.CharField(blank=True, help_text="The line's description when the pin was made - a staleness tripwire, not a key.", max_length=500)),
                ('mir_no', models.CharField(blank=True, help_text="MIR document number to match this line against. Blank means 'leave this line unmatched'.", max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_by_email', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_mir_matches', to='core.ptuser')),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'po_number'], name='core_manual_plant_c04a39_idx'), models.Index(fields=['plant', 'mir_no'], name='core_manual_plant_b8f346_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'po_number', 'item_ref'), name='uniq_manual_mir_match')],
            },
        ),
    ]
