# Generated by Django 5.2.17 on 2026-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_hrspomirmatch_manually_pinned_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='manualmirmatch',
            name='uniq_manual_mir_match',
        ),
        migrations.RemoveIndex(
            model_name='manualmirmatch',
            name='core_manual_plant_c04a39_idx',
        ),
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='manually_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualmirmatch',
            name='po_kind',
            field=models.CharField(choices=[('domestic', 'Domestic purchase order'), ('import', 'Import purchase order')], default='domestic', max_length=10),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='manually_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='manually_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='manualmirmatch',
            index=models.Index(fields=['plant', 'po_kind', 'po_number'], name='core_manual_plant_3284e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='manualmirmatch',
            constraint=models.UniqueConstraint(fields=('plant', 'po_kind', 'po_number', 'item_ref'), name='uniq_manual_mir_match'),
        ),
    ]
