# Generated by Django 5.2.17 on 2026-09-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_manualmirmatch_uniq_manual_mir_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsendlog',
            name='period_key',
            field=models.CharField(help_text="Daily report: ISO date. Monthly report: 'YYYY-MM'. Advance License expiry reports: the license_number (plant is 'all').", max_length=20),
        ),
        migrations.AlterField(
            model_name='reportsendlog',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily Consumption Report'), ('monthly', 'Monthly Consumption Report'), ('adv_import', 'Advance License Import Validity Expiry'), ('adv_export', 'Advance License Export Validity Expiry')], max_length=10),
        ),
    ]
