# Generated by Django 5.2.17 on 2026-09-22 11:58, then extended by hand with
# the data migration below - see migrate_license_keys_forward().

from django.db import migrations, models

_ADV_TYPES = {
    "adv_import": "import_validity_date",
    "adv_export": "export_validity_date",
}


def migrate_license_keys_forward(apps, schema_editor):
    """Rewrite already-claimed Advance License rows from a bare
    '<license_number>' key to '<license_number>@<validity date>'.

    Without this, every license currently inside the 30-day window would
    look unclaimed under the new key format and be alerted a SECOND time on
    the next run - the exact duplicate the dedup guard exists to prevent.
    The date written is the license's current validity date, i.e. the
    deadline that original alert was really about.

    A row whose license no longer exists (deleted/renumbered upstream) is
    left untouched: its key simply never matches again, which is harmless,
    and inventing a date for it would be worse than leaving a dead row.
    """
    ReportSendLog = apps.get_model("core", "ReportSendLog")
    AdvanceLicense = apps.get_model("core", "AdvanceLicense")

    for report_type, date_field in _ADV_TYPES.items():
        rows = ReportSendLog.objects.filter(report_type=report_type).exclude(period_key__contains="@")
        for row in rows:
            lic = AdvanceLicense.objects.filter(license_number=row.period_key).first()
            if lic is None:
                continue
            validity_date = getattr(lic, date_field)
            if validity_date is None:
                continue
            row.period_key = f"{row.period_key}@{validity_date.isoformat()}"
            row.save(update_fields=["period_key"])


def migrate_license_keys_backward(apps, schema_editor):
    """Strip the '@<date>' suffix again so the rows fit the pre-0058 key
    format (and the narrower column) if this migration is rolled back."""
    ReportSendLog = apps.get_model("core", "ReportSendLog")
    for report_type in _ADV_TYPES:
        for row in ReportSendLog.objects.filter(report_type=report_type, period_key__contains="@"):
            row.period_key = row.period_key.split("@", 1)[0]
            row.save(update_fields=["period_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_reportsendlog_period_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsendlog',
            name='period_key',
            field=models.CharField(help_text="Daily report: ISO date. Monthly report: 'YYYY-MM'. Advance License expiry reports: 'license_number@YYYY-MM-DD', the validity date being alerted on (plant is 'all').", max_length=64),
        ),
        migrations.RunPython(migrate_license_keys_forward, migrate_license_keys_backward),
    ]
