# Generated by Django 5.2.17 on 2026-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_widen_report_period_key_for_license_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='group_entries',
            field=models.ManyToManyField(blank=True, related_name='import_po_group_matches', to='core.hrsmirentry'),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='group_entries',
            field=models.ManyToManyField(blank=True, related_name='po_group_matches', to='core.hrsmirentry'),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='group_entries',
            field=models.ManyToManyField(blank=True, related_name='import_po_group_matches', to='core.rtpachhadmirentry'),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='group_entries',
            field=models.ManyToManyField(blank=True, related_name='po_group_matches', to='core.rtpachhadmirentry'),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='group_entries',
            field=models.ManyToManyField(blank=True, related_name='import_po_group_matches', to='core.rtpvapimirentry'),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='group_entries',
            field=models.ManyToManyField(blank=True, related_name='po_group_matches', to='core.rtpvapimirentry'),
        ),
    ]
