# Generated by Django 5.2.17 on 2026-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_po_match_group_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='exchange_rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='mir_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='receipt_share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='exchange_rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='mir_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='receipt_share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='exchange_rate_mismatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='mir_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='receipt_share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hrsimportpomirmatch',
            name='tier',
            field=models.CharField(choices=[('po_number', 'PO number match (exact)'), ('material', 'Material description match'), ('weighted', 'Vendor-gated weighted match (legacy, pre-2026-09 imports redesign)'), ('boe_number', 'Bill of Entry number match (exact)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rtpachhadimportpomirmatch',
            name='tier',
            field=models.CharField(choices=[('po_number', 'PO number match (exact)'), ('material', 'Material description match'), ('weighted', 'Vendor-gated weighted match (legacy, pre-2026-09 imports redesign)'), ('boe_number', 'Bill of Entry number match (exact)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rtpvapiimportpomirmatch',
            name='tier',
            field=models.CharField(choices=[('po_number', 'PO number match (exact)'), ('material', 'Material description match'), ('weighted', 'Vendor-gated weighted match (legacy, pre-2026-09 imports redesign)'), ('boe_number', 'Bill of Entry number match (exact)')], max_length=20),
        ),
    ]
