# Generated by Django 5.2.17 on 2026-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_import_boe_share_fx'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrspomirmatch',
            name='receipt_share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='manualmirmatch',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='receipt_share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='receipt_share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
