# Generated by Django 5.2.17 on 2026-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_manual_pin_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpocorrection',
            name='item_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
