# Generated by Django 5.2.17 on 2026-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_import_correction_item_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptuser',
            name='otp_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ptuser',
            name='otp_failures_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
