# Generated by Django 5.2.17 on 2026-09-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_otp_daily_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='qty_within_tolerance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='qty_within_tolerance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='qty_within_tolerance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='qty_within_tolerance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='qty_within_tolerance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='qty_within_tolerance',
            field=models.BooleanField(default=False),
        ),
    ]
