# Generated by Django 5.2.17 on 2026-09-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_qty_within_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='rolls_ordered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='rolls_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='rolls_ordered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='rolls_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='rolls_ordered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='rolls_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='rolls_ordered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='rolls_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='rolls_ordered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='rolls_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='rolls_ordered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='rolls_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
