# Generated by Django 5.2.17 on 2026-09-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_madura_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='pool_line_refs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='pool_line_refs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='pool_line_refs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='pool_line_refs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='pool_line_refs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='pool_line_refs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
