# Generated by Django 5.2.17 on 2026-09-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_pool_line_refs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('state_code', models.CharField(max_length=2)),
                ('is_union_territory', models.BooleanField(default=False)),
                ('mir_prefix', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=7)),
                ('seq', models.PositiveIntegerField()),
                ('mir_no', models.CharField(max_length=30, unique=True)),
                ('mir_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=60)),
                ('invoice_key', models.CharField(max_length=60)),
                ('invoice_date', models.DateField()),
                ('invoice_fy', models.CharField(max_length=7)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_type', models.CharField(choices=[('IGST', 'IGST'), ('CGST_SGST', 'CGST + SGST'), ('CGST_UGST', 'CGST + UGST')], max_length=12)),
                ('tax_type_expected', models.CharField(blank=True, choices=[('IGST', 'IGST'), ('CGST_SGST', 'CGST + SGST'), ('CGST_UGST', 'CGST + UGST')], default='', max_length=12)),
                ('challan_no', models.CharField(blank=True, default='', max_length=60)),
                ('lr_no', models.CharField(blank=True, default='', max_length=60)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=30)),
                ('eway_bill_no', models.CharField(blank=True, default='', max_length=30)),
                ('gate_entry_no', models.CharField(blank=True, default='', max_length=40)),
                ('weighbridge_slip_no', models.CharField(blank=True, default='', max_length=40)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=10)),
                ('created_by_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mirs', to='core.plant')),
            ],
            options={
                'ordering': ['-mir_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('qty_received', models.DecimalField(decimal_places=3, max_digits=14)),
                ('qty_rejected', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('po_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('open_qty_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=16)),
                ('taxable', models.DecimalField(decimal_places=2, max_digits=16)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('rolls', models.PositiveIntegerField(blank=True, null=True)),
                ('batch_no', models.CharField(blank=True, default='', max_length=60)),
                ('dept_use', models.CharField(blank=True, default='', max_length=60)),
                ('remarks', models.TextField(blank=True, default='')),
                ('mir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.mir')),
            ],
            options={
                'ordering': ['mir_id', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='MirReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('QTY_SHORT', 'Quantity short'), ('QTY_OVER', 'Quantity over'), ('RATE', 'Rate differs'), ('INVOICE_TOTAL', 'Invoice total differs'), ('TAX_TYPE', 'Tax type differs')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('closes_line', models.BooleanField(default=False)),
                ('note_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('closes_line', False), ('kind', 'QTY_SHORT'), _connector='OR'), name='reason_closes_only_short')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_type', models.CharField(blank=True, choices=[('IGST', 'IGST'), ('CGST_SGST', 'CGST + SGST'), ('CGST_UGST', 'CGST + UGST')], default='', max_length=12)),
                ('tax_type_raw', models.CharField(blank=True, default='', max_length=100)),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('incoterms', models.TextField(blank=True, default='')),
                ('ship_to', models.TextField(blank=True, default='')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('total_inclusive_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('item_code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('hsn', models.CharField(blank=True, default='', max_length=20)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('uom_raw', models.CharField(blank=True, default='', max_length=20)),
                ('qty_ordered', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_note', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_note', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('closed_by_mir_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mirline')),
                ('closed_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mirreasoncode')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order_id', 'line_no'],
            },
        ),
        migrations.AddField(
            model_name='mirline',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mir_lines', to='core.purchaseorderline'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.purchaseorderline')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name_key'], name='core_vendor_name_ke_053561_idx'), models.Index(fields=['vendor_code'], name='core_vendor_vendor__40558a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('gstin',), name='uniq_vendor_gstin'), models.UniqueConstraint(condition=models.Q(('gstin', '')), fields=('name_key',), name='uniq_vendor_name_without_gstin'), models.CheckConstraint(condition=models.Q(('name_key', ''), _negated=True), name='vendor_name_key_not_blank')],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='mir',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mirs', to='core.vendor'),
        ),
        migrations.CreateModel(
            name='MirMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('QTY_SHORT', 'Quantity short'), ('QTY_OVER', 'Quantity over'), ('RATE_HIGH', 'Rate higher than PO'), ('RATE_LOW', 'Rate lower than PO'), ('INVOICE_TOTAL', 'Invoice total differs'), ('TAX_TYPE', 'Tax type differs')], max_length=20)),
                ('expected', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('difference_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('VOID', 'Void')], default='OPEN', max_length=10)),
                ('resolved_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('mir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='core.mir')),
                ('mir_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mismatches', to='core.mirline')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.mirreasoncode')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'kind'], name='core_mirmis_status_bc3b7c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mir_line__isnull', False)), fields=('mir_line', 'kind'), name='uniq_mismatch_per_line_kind'), models.UniqueConstraint(condition=models.Q(('mir_line__isnull', True)), fields=('mir', 'kind'), name='uniq_mismatch_per_mir_kind'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'RESOLVED'), _negated=True), models.Q(('resolved_at__isnull', False), models.Q(('resolution_note', ''), _negated=True)), _connector='OR'), name='mismatch_resolution_has_note')],
            },
        ),
        migrations.CreateModel(
            name='MirSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=7)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.plant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'fy'), name='uniq_mir_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_no'), name='uniq_po_line_position'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('line_no__gte', 1)), name='po_line_no_positive'),
        ),
        migrations.AddConstraint(
            model_name='mirline',
            constraint=models.UniqueConstraint(fields=('mir', 'line_no'), name='uniq_mir_line_no'),
        ),
        migrations.AddConstraint(
            model_name='mirline',
            constraint=models.UniqueConstraint(fields=('mir', 'po_line'), name='uniq_po_line_once_per_mir'),
        ),
        migrations.AddConstraint(
            model_name='mirline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_received__gt', 0)), name='mir_qty_received_positive'),
        ),
        migrations.AddConstraint(
            model_name='mirline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_rejected__gte', 0), ('qty_rejected__lte', models.F('qty_received'))), name='mir_qty_rejected_within_received'),
        ),
        migrations.AddConstraint(
            model_name='mirline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('discount__gte', 0), ('other_charges__gte', 0), ('gst_rate__gte', 0), ('gst_rate__lte', 40)), name='mir_line_figures_valid'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='core_purcha_po_numb_14c4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['is_active'], name='core_purcha_is_acti_c5674d_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('plant', 'po_number'), name='uniq_po_per_plant'),
        ),
        migrations.AddIndex(
            model_name='mir',
            index=models.Index(fields=['plant', 'mir_date'], name='core_mir_plant_i_454b02_idx'),
        ),
        migrations.AddIndex(
            model_name='mir',
            index=models.Index(fields=['invoice_key'], name='core_mir_invoice_93b90d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mir',
            constraint=models.UniqueConstraint(fields=('plant', 'fy', 'seq'), name='uniq_mir_seq_per_plant_fy'),
        ),
        migrations.AddConstraint(
            model_name='mir',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'POSTED')), fields=('vendor', 'invoice_key', 'invoice_fy'), name='uniq_posted_mir_per_vendor_invoice'),
        ),
        migrations.AddConstraint(
            model_name='mir',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_date__lte', models.F('mir_date'))), name='mir_invoice_not_after_receipt'),
        ),
        migrations.AddConstraint(
            model_name='mir',
            constraint=models.CheckConstraint(condition=models.Q(('invoice_total__gte', 0), ('tcs_amount__gte', 0)), name='mir_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='mir',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'POSTED'), models.Q(('cancelled_at__isnull', False), models.Q(('cancel_reason', ''), _negated=True)), _connector='OR'), name='mir_cancel_has_reason'),
        ),
    ]
