# Generated by Django 5.2.17 on 2026-09-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_seed_procurement_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="SortPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        choices=[("materials", "Raw Material Analysis")], max_length=30
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("levels", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sort_presets",
                        to="core.ptuser",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "view", "name"),
                        name="uniq_sort_preset_name_per_user_view",
                    )
                ],
            },
        ),
    ]
