# Generated by Django 5.2.17 on 2026-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_sort_preset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sortpreset",
            name="view",
            field=models.CharField(
                choices=[
                    ("materials", "Raw Material Analysis"),
                    ("purchase_orders", "Purchase Orders (Domestic)"),
                    ("import_purchases", "Import Purchases"),
                ],
                max_length=30,
            ),
        ),
    ]
