# Generated by Django 5.2.17 on 2026-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_sort_preset_more_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sortpreset",
            name="view",
            field=models.CharField(
                choices=[
                    ("materials", "Raw Material Analysis"),
                    ("purchase_orders", "Purchase Orders (Domestic)"),
                    ("import_purchases", "Import Purchases"),
                    ("material_lots", "Raw Material modal: Stock by Plant"),
                    ("material_open_pos", "Raw Material modal: Open Purchase Orders"),
                ],
                max_length=30,
            ),
        ),
    ]
