# Generated by Django 5.2.17 on 2026-09-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_sort_preset_po_modal_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sortpreset",
            name="view",
            field=models.CharField(
                choices=[
                    ("materials", "Raw Material Analysis"),
                    ("purchase_orders", "Purchase Orders (Domestic)"),
                    ("import_purchases", "Import Purchases"),
                    ("material_lots", "Raw Material modal: Stock by Plant"),
                    ("material_open_pos", "Raw Material modal: Open Purchase Orders"),
                    ("po_lines", "PO modal: line items"),
                    ("po_receipts", "PO modal: MIR receipts"),
                    ("search_po", "Search PO: results"),
                    ("search_po_items", "Search PO: line items"),
                ],
                max_length=30,
            ),
        ),
    ]
