# Generated by Django 5.2.17 on 2026-09-29 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_sort_preset_search_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsimportpomirmatch',
            name='receipt_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hrspomirmatch',
            name='receipt_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rtpachhadimportpomirmatch',
            name='receipt_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rtpachhadpomirmatch',
            name='receipt_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rtpvapiimportpomirmatch',
            name='receipt_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rtpvapipomirmatch',
            name='receipt_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ManualReceiptEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20)),
                ('po_kind', models.CharField(choices=[('domestic', 'Domestic purchase order'), ('import', 'Import purchase order')], default='domestic', max_length=10)),
                ('po_number', models.CharField(max_length=100)),
                ('item_ref', models.CharField(max_length=50)),
                ('item_description', models.CharField(blank=True, max_length=500)),
                ('mir_no', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('add', 'Add this receipt to the line'), ('remove', 'Remove this receipt from the line')], max_length=10)),
                ('shared', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('created_by_email', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_receipt_edits', to='core.ptuser')),
            ],
            options={
                'indexes': [models.Index(fields=['plant', 'po_kind', 'po_number'], name='core_manual_plant_a59af2_idx'), models.Index(fields=['plant', 'mir_no'], name='core_manual_plant_eb6fe8_idx')],
                'constraints': [models.UniqueConstraint(fields=('plant', 'po_kind', 'po_number', 'item_ref', 'mir_no'), name='uniq_manual_receipt_edit')],
            },
        ),
    ]
