# Generated by Django 5.2.17 on 2026-09-29 06:37
"""Review verdicts and match dismissals keyed on the pair a match joins,
not the match row's id (see apps/services/match_pairs.py).

Backfill: every existing MatchReview gets the pair of the match row it
points at, where that row still exists; a verdict whose row is already gone
keeps null pair columns and scores as stale, as it did before. Every match
row currently dismissed gets a MatchDismissal, so the dismissals made so far
survive their next re-match too. Model names are listed here rather than
read from the matching configs, so the migration does not depend on
services code that may change."""

import django.db.models.deletion
from django.db import migrations, models


_MODELS = {
    ("HRS", "po_mir"): ("HRSPOMirMatch", "po_line_item_id", "mir_entry_id"),
    ("RTP-ACHHAD", "po_mir"): ("RTPAchhadPOMirMatch", "po_line_item_id", "mir_entry_id"),
    ("RTP-VAPI", "po_mir"): ("RTPVapiPOMirMatch", "po_line_item_id", "mir_entry_id"),
    ("HRS", "import_po_mir"): ("HRSImportPOMirMatch", "po_line_item_id", "mir_entry_id"),
    ("RTP-ACHHAD", "import_po_mir"): ("RTPAchhadImportPOMirMatch", "po_line_item_id", "mir_entry_id"),
    ("RTP-VAPI", "import_po_mir"): ("RTPVapiImportPOMirMatch", "po_line_item_id", "mir_entry_id"),
    ("HRS", "mir_stock"): ("HRSMirStockMatch", "mir_entry_id", "stock_lot_id"),
    ("RTP-ACHHAD", "mir_stock"): ("RTPAchhadMirStockMatch", "mir_entry_id", "stock_lot_id"),
    ("RTP-VAPI", "mir_stock"): ("RTPVapiMirStockMatch", "mir_entry_id", "stock_lot_id"),
}


def backfill(apps, schema_editor):
    MatchReview = apps.get_model("core", "MatchReview")
    MatchDismissal = apps.get_model("core", "MatchDismissal")
    for (plant, match_type), (name, left, right) in _MODELS.items():
        model = apps.get_model("core", name)
        pairs = {pk: (l, r) for pk, l, r in model.objects.values_list("pk", left, right)}
        for review in MatchReview.objects.filter(plant=plant, match_type=match_type, left_id__isnull=True):
            pair = pairs.get(review.match_id)
            if pair is not None:
                review.left_id, review.right_id = pair
                review.save(update_fields=["left_id", "right_id"])
        for row in model.objects.filter(dismissed_by_override=True):
            MatchDismissal.objects.get_or_create(
                plant=plant, match_type=match_type, left_id=getattr(row, left), right_id=getattr(row, right),
                defaults=dict(
                    dismissed_by_id=row.dismissed_by_id,
                    dismissed_reason=row.dismissed_reason,
                    dismissed_at=row.dismissed_at or row.computed_at,
                ),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_manual_receipt_edits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(choices=[('HRS', 'Hindustan Rubbers, Silvassa'), ('RTP-VAPI', 'Ravasco Transmission and Packing, Vapi'), ('RTP-ACHHAD', 'Ravasco Transmission and Packing, Achhad'), ('COMPANY', 'Company-wide (not plant-specific)')], max_length=20)),
                ('match_type', models.CharField(choices=[('po_mir', 'PO <-> MIR'), ('import_po_mir', 'Import PO <-> MIR'), ('mir_stock', 'MIR <-> Stock')], max_length=20)),
                ('left_id', models.PositiveIntegerField()),
                ('right_id', models.PositiveIntegerField()),
                ('dismissed_reason', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='matchreview',
            name='left_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchreview',
            name='right_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='matchreview',
            index=models.Index(fields=['plant', 'match_type', 'left_id', 'right_id'], name='core_matchr_plant_06b22a_idx'),
        ),
        migrations.AddField(
            model_name='matchdismissal',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_dismissals', to='core.ptuser'),
        ),
        migrations.AddConstraint(
            model_name='matchdismissal',
            constraint=models.UniqueConstraint(fields=('plant', 'match_type', 'left_id', 'right_id'), name='uniq_match_dismissal_pair'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
