# Generated by Django 5.2.17 on 2026-09-29 08:35

import importlib

from django.db import migrations, models

_SEED = importlib.import_module("apps.core.migrations.0068_seed_procurement_reference")

LEGACY_PO_MODELS = {
    "hrs": "HRSDomesticPurchaseOrder",
    "achhad": "RTPAchhadDomesticPurchaseOrder",
    "vapi": "RTPVapiDomesticPurchaseOrder",
}


def forwards(apps, schema_editor):
    """The new reasons (0068's list is the one source), and each PO's Bill
    To copied from its plant's CSV mirror - the projection skips an order
    whose mirror hash has not changed, so it would never fill them."""
    _SEED.seed(apps, schema_editor)
    PurchaseOrder = apps.get_model("core", "PurchaseOrder")
    for plant_code, name in LEGACY_PO_MODELS.items():
        legacy = dict(apps.get_model("core", name).objects.exclude(billing_address="").values_list("po_number", "billing_address"))
        for po in PurchaseOrder.objects.filter(plant__code=plant_code, billing_address=""):
            if legacy.get(po.po_number):
                po.billing_address = legacy[po.po_number]
                po.save(update_fields=["billing_address"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_match_decisions_keyed_on_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mir',
            name='uniq_posted_mir_per_vendor_invoice',
        ),
        migrations.AddField(
            model_name='mir',
            name='sap_grn_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mirline',
            name='material_category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mirline',
            name='material_subcategory',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mirmismatch',
            name='kind',
            field=models.CharField(choices=[('QTY_SHORT', 'Quantity short'), ('QTY_OVER', 'Quantity over'), ('RATE_HIGH', 'Rate higher than PO'), ('RATE_LOW', 'Rate lower than PO'), ('INVOICE_TOTAL', 'Invoice total differs'), ('TAX_TYPE', 'Tax type differs'), ('QTY_REJECTED', 'Quantity rejected'), ('GST_RATE', 'GST rate differs from PO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mirreasoncode',
            name='kind',
            field=models.CharField(choices=[('QTY_SHORT', 'Quantity short'), ('QTY_OVER', 'Quantity over'), ('RATE', 'Rate differs'), ('INVOICE_TOTAL', 'Invoice total differs'), ('TAX_TYPE', 'Tax type differs'), ('REJECTION', 'Quantity rejected'), ('GST_RATE', 'GST rate differs')], max_length=20),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
