# Generated by Django 5.2.17 on 2026-09-29 09:20

"""The material master (see Material's docstring) and MIR edit history.

Data steps, in order, before MirLine's own category columns are dropped:
  1. one Material per MaterialCategoryReference row, keyed on the row's own
     normalized_description (the key the dashboard files stock lots by), with
     its category;
  2. every procurement PO line linked to a Material by its description
     (created when new, filed from the reference row carrying its SAP item
     code when exactly one does, otherwise left uncategorised);
  3. a category already chosen on a posted MIR line copied onto its
     material where the material has none - nothing a clerk filed is lost.

material_identity.py (and the parsers/common.py it uses) is kept free of
Django imports for exactly this use."""

import django.db.models.deletion
from django.db import migrations, models

from apps.services.material_identity import material_key, material_name


def forwards(apps, schema_editor):
    Material = apps.get_model("core", "Material")
    Reference = apps.get_model("core", "MaterialCategoryReference")
    Line = apps.get_model("core", "PurchaseOrderLine")
    MirLine = apps.get_model("core", "MirLine")

    by_key = {}
    code_rows = {}
    for ref in Reference.objects.exclude(sap_item_code=""):
        code_rows.setdefault(ref.sap_item_code.strip(), []).append(ref)
    for ref in Reference.objects.all():
        key = ref.normalized_description
        if not key or key in by_key:
            continue
        by_key[key] = Material.objects.create(
            name=ref.description.strip()[:500], name_key=key, item_code=(ref.sap_item_code or "").strip()[:50],
            uom=(ref.uom or "").strip()[:20], hsn=(ref.hsn_code or "").strip()[:20],
            category=(ref.category or "").strip(), subcategory=(ref.subcategory or "").strip(),
        )
    for line in Line.objects.filter(material__isnull=True).order_by("id"):
        key = material_key(line.description)
        if not key:
            continue
        material = by_key.get(key)
        if material is None:
            by_code = code_rows.get((line.item_code or "").strip(), [])
            ref = by_code[0] if len(by_code) == 1 else None
            material = by_key[key] = Material.objects.create(
                name=material_name(line.description)[:500], name_key=key, item_code=(line.item_code or "")[:50],
                uom=line.uom or "", hsn=line.hsn or "",
                category=(ref.category or "").strip() if ref else "", subcategory=(ref.subcategory or "").strip() if ref else "",
            )
        line.material = material
        line.save(update_fields=["material"])
    for ml in MirLine.objects.exclude(material_category="").select_related("po_line__material").order_by("id"):
        material = ml.po_line.material
        if material is not None and not material.category:
            material.category, material.subcategory = ml.material_category, ml.material_subcategory
            material.category_set_by_email = ml.mir.created_by_email
            material.category_set_at = ml.mir.created_at
            material.save(update_fields=["category", "subcategory", "category_set_by_email", "category_set_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_mir_form_fields_and_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_key', models.CharField(max_length=500, unique=True)),
                ('item_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('hsn', models.CharField(blank=True, default='', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('subcategory', models.CharField(blank=True, default='', max_length=200)),
                ('category_set_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('category_set_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='core_materi_categor_0330dd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('name_key', ''), _negated=True), name='material_name_key_not_blank')],
            },
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='core.material'),
        ),
        migrations.CreateModel(
            name='MirChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField()),
                ('changed_by_email', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('mir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.mir')),
                ('mir_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.mirline')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='mir_change_has_reason')],
            },
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='mirline',
            name='material_category',
        ),
        migrations.RemoveField(
            model_name='mirline',
            name='material_subcategory',
        ),
    ]
