# Generated by Django 5.2.17 on 2026-09-29 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_material_master_and_mir_edits'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField()),
                ('changed_by_email', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='core.material')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='material_change_has_reason')],
            },
        ),
    ]
