# Generated by Django 5.2.17 on 2026-09-29 10:12

"""The INVOICE_DATE reason kind and its reasons (an invoice dated before its
PO). The reason list lives in 0068's REASONS; its seed() is re-run here so a
database that already applied 0068 gets the new rows."""

import importlib

from django.db import migrations, models

_SEED = importlib.import_module("apps.core.migrations.0068_seed_procurement_reference")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_material_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirmismatch',
            name='kind',
            field=models.CharField(choices=[('QTY_SHORT', 'Quantity short'), ('QTY_OVER', 'Quantity over'), ('RATE_HIGH', 'Rate higher than PO'), ('RATE_LOW', 'Rate lower than PO'), ('INVOICE_TOTAL', 'Invoice total differs'), ('TAX_TYPE', 'Tax type differs'), ('QTY_REJECTED', 'Quantity rejected'), ('GST_RATE', 'GST rate differs from PO'), ('INVOICE_BEFORE_PO', 'Invoice dated before the PO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mirreasoncode',
            name='kind',
            field=models.CharField(choices=[('QTY_SHORT', 'Quantity short'), ('QTY_OVER', 'Quantity over'), ('RATE', 'Rate differs'), ('INVOICE_TOTAL', 'Invoice total differs'), ('TAX_TYPE', 'Tax type differs'), ('REJECTION', 'Quantity rejected'), ('GST_RATE', 'GST rate differs'), ('INVOICE_DATE', 'Invoice dated before the PO')], max_length=20),
        ),
        migrations.RunPython(_SEED.seed, migrations.RunPython.noop),
    ]
