# Generated by Django 5.2.17 on 2026-09-29 11:50

import django.db.models.deletion
from django.db import migrations, models

from apps.services import stock_rules

REASONS = [
    # code, kind, label, note_required
    # The one list of stock reasons (RM stock entry, 2026-09-29). A later
    # migration that adds one re-runs seed() (the way 0076 re-runs 0068's),
    # and the root conftest.py re-seeds from here for tests. Reasons are never
    # deleted: a posted voucher line points at its reason with PROTECT.
    ("RETURN_UNUSED", "RETURN", "Not used - returned to store", False),
    ("RETURN_EXCESS", "RETURN", "More was issued than needed", False),
    ("RETURN_WRONG_MATERIAL", "RETURN", "Wrong material or grade issued", False),
    ("RETURN_OTHER", "RETURN", "Other (explain in the note)", True),
    ("OPENING_BALANCE", "ADJUST_IN", "Opening balance when stock entry started", False),
    ("COUNT_GAIN", "ADJUST_IN", "Physical count found more than the books", True),
    ("ADD_OTHER", "ADJUST_IN", "Other (explain in the note)", True),
    ("COUNT_LOSS", "ADJUST_OUT", "Physical count found less than the books", True),
    ("DAMAGED_EXPIRED", "ADJUST_OUT", "Damaged, contaminated or expired", True),
    ("HANDLING_LOSS", "ADJUST_OUT", "Spillage or handling loss", True),
    ("SAMPLE_TESTING", "ADJUST_OUT", "Taken as a sample or for testing", False),
    ("WRITE_OFF_OTHER", "ADJUST_OUT", "Other (explain in the note)", True),
]


def seed(apps, schema_editor):
    Reason = apps.get_model("core", "StockReasonCode")
    for order, (code, kind, label, note) in enumerate(REASONS):
        Reason.objects.update_or_create(
            code=code, defaults={"kind": kind, "label": label, "note_required": note, "sort_order": order},
        )


def lots_for_existing_mirs(apps, schema_editor):
    """Every MIR line posted before stock entry existed gets its lot, exactly
    as stock_service.receive_mir() makes one at posting - so the store's
    stock starts from every receipt already in the app. A cancelled MIR's
    lot holds nothing, as it would had it been cancelled after this."""
    MirLine = apps.get_model("core", "MirLine")
    StockLot = apps.get_model("core", "StockLot")
    lines = MirLine.objects.select_related("mir", "po_line__purchase_order").filter(po_line__material__isnull=False)
    for line in lines.iterator():
        if StockLot.objects.filter(mir_line=line).exists():
            continue
        mir, po_line = line.mir, line.po_line
        uom, factor = stock_rules.stock_unit(po_line.uom)
        po = po_line.purchase_order
        StockLot.objects.create(
            plant_id=mir.plant_id, material_id=po_line.material_id, uom=uom, source="MIR", mir_line=line,
            received_date=mir.mir_date, vendor_id=mir.vendor_id,
            bill_to_plant_id=po.plant_id if po.plant_id != mir.plant_id else None,
            factor=factor, rate=stock_rules.lot_rate(line.taxable, line.qty_received, factor),
            currency=po.currency or "INR", stocked=True, batch_no=line.batch_no,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_sort_preset_plant_combined_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('RETURN', 'Returned to store'), ('ADJUST_IN', 'Stock added'), ('ADJUST_OUT', 'Stock written off')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('note_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ISSUE', 'Issue'), ('RETURN', 'Return to store'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('fy', models.CharField(max_length=7)),
                ('seq', models.PositiveIntegerField()),
                ('voucher_no', models.CharField(max_length=40, unique=True)),
                ('voucher_date', models.DateField()),
                ('department', models.CharField(blank=True, default='', max_length=60)),
                ('issued_to', models.CharField(blank=True, default='', max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for approval'), ('POSTED', 'Posted'), ('REJECTED', 'Not approved'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=10)),
                ('created_by_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('cancelled_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_vouchers', to='core.plant')),
                ('return_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='core.stockvoucher')),
            ],
            options={
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('direction', models.SmallIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('book_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.material')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.stockreasoncode')),
                ('return_of_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_by', to='core.stockvoucherline')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.stockvoucher')),
            ],
            options={
                'ordering': ['voucher_id', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('MIR', 'MIR receipt'), ('ADJUSTMENT', 'Adjustment')], max_length=12)),
                ('received_date', models.DateField()),
                ('factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('stocked', models.BooleanField(default=True)),
                ('batch_no', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_to_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.plant')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='core.material')),
                ('mir_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_lot', to='core.mirline')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='core.plant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.vendor')),
                ('voucher_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_lot', to='core.stockvoucherline')),
            ],
            options={
                'ordering': ['received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.stocklot')),
                ('voucher_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.stockvoucherline')),
            ],
        ),
        migrations.CreateModel(
            name='StockSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('fy', models.CharField(max_length=7)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.plant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'kind', 'fy'), name='uniq_stock_sequence')],
            },
        ),
        migrations.CreateModel(
            name='StockSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stocked', models.BooleanField(default=True)),
                ('min_level', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('min_level_uom', models.CharField(blank=True, default='', max_length=20)),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_settings', to='core.material')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.plant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ptuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plant', 'material'), name='uniq_stock_setting'), models.CheckConstraint(condition=models.Q(('min_level__isnull', True), ('min_level__gte', 0), _connector='OR'), name='stock_min_level_not_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='stockvoucher',
            index=models.Index(fields=['plant', 'voucher_date'], name='core_stockv_plant_i_dd8b52_idx'),
        ),
        migrations.AddIndex(
            model_name='stockvoucher',
            index=models.Index(fields=['status', 'kind'], name='core_stockv_status_523fec_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucher',
            constraint=models.UniqueConstraint(fields=('plant', 'kind', 'fy', 'seq'), name='uniq_stock_voucher_seq'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('return_of__isnull', True), ('kind', 'RETURN'), _connector='OR'), name='stock_return_of_only_on_return'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'RETURN'), ('return_of__isnull', False)), models.Q(('kind', 'RETURN'), _negated=True), _connector='OR'), name='stock_return_names_its_issue'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'ISSUE'), _negated=True), models.Q(('department', ''), _negated=True), _connector='OR'), name='stock_issue_has_department'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PENDING'), models.Q(('kind', 'ADJUST'), _negated=True), ('decided_at__isnull', False), _connector='OR'), name='stock_adjustment_decided'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancelled_at__isnull', False), models.Q(('cancel_reason', ''), _negated=True)), _connector='OR'), name='stock_cancel_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PENDING'), ('status', 'POSTED'), ('status', 'CANCELLED'), ('kind', 'ADJUST'), _connector='OR'), name='stock_only_adjustments_rejected'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucherline',
            constraint=models.UniqueConstraint(fields=('voucher', 'line_no'), name='uniq_stock_voucher_line_no'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucherline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='stock_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucherline',
            constraint=models.CheckConstraint(condition=models.Q(('direction', 1), ('direction', -1), _connector='OR'), name='stock_line_direction'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucherline',
            constraint=models.CheckConstraint(condition=models.Q(('rate__isnull', True), ('rate__gte', 0), _connector='OR'), name='stock_line_rate_not_negative'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['plant', 'material', 'uom'], name='core_stockl_plant_i_ca89d9_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['received_date'], name='core_stockl_receive_0b5c34_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mir_line__isnull', False), ('source', 'MIR'), ('voucher_line__isnull', True)), models.Q(('mir_line__isnull', True), ('source', 'ADJUSTMENT'), ('voucher_line__isnull', False)), _connector='OR'), name='stock_lot_has_one_source'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('factor__gt', 0)), name='stock_lot_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='stock_allocation_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockallocation',
            constraint=models.UniqueConstraint(fields=('voucher_line', 'lot'), name='uniq_stock_allocation'),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
        migrations.RunPython(lots_for_existing_mirs, migrations.RunPython.noop),
    ]
