# Generated by Django 5.2.17 on 2026-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_material_base_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="source",
            field=models.CharField(
                choices=[
                    ("csv", "PO master CSV (Drive)"),
                    ("app", "Entered in the app"),
                ],
                default="csv",
                max_length=10,
            ),
        ),
    ]
