# Generated by Django 5.2.17 on 2026-09-30 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_purchase_order_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PO", "Purchase order"), ("INVOICE", "Invoice")],
                        max_length=10,
                    ),
                ),
                ("po_number", models.CharField(blank=True, default="", max_length=100)),
                ("revision", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("SUPERSEDED", "Superseded by a newer revision"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="CURRENT",
                        max_length=12,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True, default="")),
                ("uploaded_by_email", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "withdrawn_by_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdraw_reason", models.TextField(blank=True, default="")),
                (
                    "mir",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.mir",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.plant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.ptuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["kind", "plant", "po_number"],
                        name="core_docume_kind_e9da1a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_docume_status_daedd3_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "PO")),
                        fields=("plant", "po_number", "revision"),
                        name="uniq_po_document_revision",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "INVOICE")),
                        fields=("mir", "revision"),
                        name="uniq_invoice_document_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "INVOICE"),
                                ("mir__isnull", False),
                                ("po_number", ""),
                            ),
                            models.Q(
                                ("kind", "PO"),
                                ("mir__isnull", True),
                                models.Q(("po_number", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="document_kind_shape",
                    ),
                ],
            },
        ),
    ]
