# Generated by Django 5.2.17 on 2026-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_delete_matchreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptuser',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
