# Generated by Django 5.2.17 on 2026-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_ptuser_last_seen_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='document_kind_shape',
        ),
        migrations.AddField(
            model_name='document',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('PO', 'Purchase order'), ('INVOICE', 'Invoice'), ('BOE', 'Bill of Entry'), ('ADV_LIC', 'Advance License'), ('RODTEP', 'RoDTEP scrip')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ('BOE', 'ADV_LIC', 'RODTEP'))), fields=('kind', 'plant', 'po_number', 'reference', 'revision'), name='uniq_import_document_revision'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'INVOICE'), ('mir__isnull', False), ('po_number', ''), ('reference', '')), models.Q(('kind', 'PO'), ('mir__isnull', True), ('reference', ''), models.Q(('po_number', ''), _negated=True)), models.Q(('kind__in', ('BOE', 'ADV_LIC', 'RODTEP')), ('mir__isnull', True), models.Q(('po_number', ''), _negated=True), models.Q(('reference', ''), _negated=True)), _connector='OR'), name='document_kind_shape'),
        ),
    ]
