# Generated by Django 5.2.17 on 2026-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_ptuser_layered_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Sign-in on a new device'), ('password_change', 'Password change (signed in)'), ('password_reset', 'Forgotten password reset')], default='login', max_length=20),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='otpcode',
            constraint=models.UniqueConstraint(fields=('email', 'purpose'), name='uniq_otp_email_purpose'),
        ),
    ]
