# Generated by Django 5.2.17 on 2026-10-03 05:37

from django.db import migrations, models

from apps.services.procurement_rules import gstin_state


def backfill(apps, schema_editor):
    """Every posted line gets the PO line's description and unit it was
    entered against (no PO sheet change has reached a posted line's unit
    without a review flag), and every MIR its vendor's GSTIN state."""
    Mir = apps.get_model("core", "Mir")
    MirLine = apps.get_model("core", "MirLine")
    for ml in MirLine.objects.select_related("po_line").iterator():
        MirLine.objects.filter(pk=ml.pk).update(description=ml.po_line.description[:500], uom=ml.po_line.uom[:20])
    for mir in Mir.objects.select_related("vendor").iterator():
        state = gstin_state(mir.vendor.gstin)
        if state:
            Mir.objects.filter(pk=mir.pk).update(vendor_state=state)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_purchase_order_billing_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mir',
            name='vendor_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='mirline',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mirline',
            name='uom',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
