# Generated by Django 5.2.17 on 2026-10-03 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_mir_vendor_state_and_line_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='location_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='location_set_by_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_key', models.CharField(max_length=60)),
                ('created_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_locations', to='core.plant')),
            ],
            options={
                'ordering': ['plant_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stocklot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.stocklocation'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(fields=('plant', 'name_key'), name='uniq_stock_location_per_plant'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.CheckConstraint(condition=models.Q(('name_key', ''), _negated=True), name='stock_location_named'),
        ),
    ]
