# Generated by Django 5.2.17 on 2026-10-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_stock_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantStockSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('drive', 'Drive sheets'), ('app', 'In-app MIR and RM store')], default='drive', max_length=10)),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_source', to='core.plant')),
            ],
        ),
    ]
