# Generated by Django 5.2.17 on 2026-10-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_plant_stock_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Waiting for the background worker'), ('RUNNING', 'Reading the PO'), ('READY', 'Ready for review'), ('FAILED', 'Could not read it'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=10)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('draft', models.JSONField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('requested_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='core.document')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_extractions', to='core.plant')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='core.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['plant', 'status'], name='core_poextr_plant_i_160791_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('purchase_order__isnull', False), _connector='OR'), name='po_extraction_approved_has_po'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('review_note', ''), _negated=True), _connector='OR'), name='po_extraction_rejected_has_reason')],
            },
        ),
    ]
