# Generated by Django 5.2.17 on 2026-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_po_extraction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='uniq_po_per_plant',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='kind',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('import', 'Import')], default='domestic', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('plant', 'kind', 'po_number'), name='uniq_po_per_plant_kind'),
        ),
    ]
