# Generated by Django 5.2.17 on 2026-10-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_purchase_order_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boe_number', models.CharField(max_length=50)),
                ('bill_of_lading_number', models.CharField(blank=True, default='', max_length=100)),
                ('boe_date', models.DateField(blank=True, null=True)),
                ('laden_on_board_date', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('currency_after_taxes', models.CharField(blank=True, default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_inclusive_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('source', models.CharField(choices=[('csv', 'Import PO sheet (Drive)'), ('app', 'Approved BOE reading')], default='csv', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-boe_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_as_per_boe', models.DecimalField(decimal_places=3, max_digits=14)),
                ('total_inclusive_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('license_type', models.CharField(blank=True, default='', max_length=20)),
                ('license_number', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['shipment_id', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='poextraction',
            name='po_extraction_approved_has_po',
        ),
        migrations.AddField(
            model_name='poextraction',
            name='kind',
            field=models.CharField(choices=[('PO', 'Purchase order'), ('BOE', 'Bill of Entry')], default='PO', max_length=4),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.document'),
        ),
        migrations.AddField(
            model_name='importshipment',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_shipments', to='core.plant'),
        ),
        migrations.AddField(
            model_name='mir',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mirs', to='core.importshipment'),
        ),
        migrations.AddField(
            model_name='poextraction',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractions', to='core.importshipment'),
        ),
        migrations.AddConstraint(
            model_name='poextraction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'APPROVED'), _negated=True), ('purchase_order__isnull', False), ('shipment__isnull', False), _connector='OR'), name='po_extraction_approved_has_record'),
        ),
        migrations.AddField(
            model_name='importshipmentline',
            name='po_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='core.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='importshipmentline',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.importshipment'),
        ),
        migrations.AddField(
            model_name='mirline',
            name='shipment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mir_lines', to='core.importshipmentline'),
        ),
        migrations.AddConstraint(
            model_name='importshipment',
            constraint=models.UniqueConstraint(fields=('plant', 'boe_number', 'bill_of_lading_number'), name='uniq_import_shipment'),
        ),
        migrations.AddConstraint(
            model_name='importshipment',
            constraint=models.CheckConstraint(condition=models.Q(('boe_number', ''), _negated=True), name='import_shipment_has_boe'),
        ),
        migrations.AddConstraint(
            model_name='importshipmentline',
            constraint=models.UniqueConstraint(fields=('shipment', 'po_line'), name='uniq_shipment_po_line'),
        ),
        migrations.AddConstraint(
            model_name='importshipmentline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_as_per_boe__gt', 0)), name='shipment_line_qty_positive'),
        ),
    ]
