# Generated by Django 5.2.17 on 2026-10-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_import_shipments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceDebit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('ADVANCE', 'Advance Authorisation'), ('RODTEP', 'RoDTEP scrip')], max_length=10)),
                ('license_number', models.CharField(max_length=50)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('value_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('duty_foregone', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licence_debits', to='core.importshipmentline')),
            ],
            options={
                'ordering': ['shipment_line_id', 'id'],
                'indexes': [models.Index(fields=['license_type', 'license_number'], name='core_licenc_license_7b9c20_idx')],
            },
        ),
    ]
