# Generated by Django 5.2.17 on 2026-10-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_licence_debits'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantstocksource',
            name='import_source',
            field=models.CharField(choices=[('drive', 'Drive sheets'), ('app', 'In-app MIR and RM store')], default='drive', max_length=10),
        ),
    ]
